version: '3.8'

services:
  website-client:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILD_VERSION: ${BUILD_VERSION:-0.0.137}
        BUILD_TIMESTAMP: ${BUILD_TIMESTAMP:-}
        BUILD_SHA: ${BUILD_SHA:-}
    ports:
      - "3001:80"
    restart: unless-stopped
